### PR TITLE
Convert registration util to a library

### PR DESCRIPTION
**Pull request by MarkNSweep**
Enhance the registration tool to also be able to operate as a shared library imported through jitpack. Also minor fix to the GET invocation so that it does not accidentally convert the method to a POST by creating an output stream. Also renamed the packages and converted the final output to an executable jar.

---

This change is [Reviewable](https://reviewable.io/reviews/gameontext/regutil/1)

### CODE REVIEW

**Comment by ebullient** [comment]
Reviewed 9 of 10 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[regutil-app/src/test/reg.json, line 3 [r1]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KMZxjT4TyKIhfyog_mF:-KMZxjT56bZWyg6RUxqh:1422067184) ([raw file](https://github.com/gameontext/regutil/blob/22298df789a9288d48e7ff47abafedee83b3b120/regutil-app/src/test/reg.json#L3)):_

> ``` JSON
> {
> "name":"JSReg",
> "fullName":"A room registered by JSReg tm.",
> ```

?? How about gameontext registration utility or something boring like that. This is def not JavaScript.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1)_

**Comment by ebullient** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[regutil-app/src/test/reg.json, line 3 [r1]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KMZxjT4TyKIhfyog_mF:-KMZxjT56bZWyg6RUxqh:-687387117) ([raw file](https://github.com/gameontext/regutil/blob/22298df789a9288d48e7ff47abafedee83b3b120/regutil-app/src/test/reg.json#L3)):_

> ``` JSON
> {
> "name":"JSReg",
> "fullName":"A room registered by JSReg tm.",
> ```

?? How about gameontext registration utility or something boring like that. This is def not JavaScript. 

"name": "GOReg"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1)_

**Comment by ebullient** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1)_

**Comment by MarkNSweep** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[regutil-app/src/test/reg.json, line 3 [r1]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KMZxjT4TyKIhfyog_mF:-KM_KcB2yqk3HJySZDGi:2110099096) ([raw file](https://github.com/gameontext/regutil/blob/22298df789a9288d48e7ff47abafedee83b3b120/regutil-app/src/test/reg.json#L3)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



> ?? How about gameontext registration utility or something boring like that. This is def not JavaScript. 
> 
> "name": "GOReg"
> 
> </details>
> Oops, this was left in from when I modified the file to test the JavaScript HMAC code. I'll change it back to something more appropriate.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1)_

**Comment by ebullient** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[regutil-app/src/test/reg.json, line 2 [r2]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KM_Yc_bjWGgJ2CZz9at:-KM_Yc_bjWGgJ2CZz9au:-1203125881) ([raw file](https://github.com/gameontext/regutil/blob/3cfc5fca55ca958e106e7212a22ba0038d06b79c/regutil-app/src/test/reg.json#L2)):_

> ``` JSON
> {
> "name":"GoReg",
> ```

roomShortname

---

_[regutil-app/src/test/reg.json, line 3 [r2]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KM_YREr6hS_T9qfkrnS:-KM_YREs0nNWeIbsWh6m:285135518) ([raw file](https://github.com/gameontext/regutil/blob/3cfc5fca55ca958e106e7212a22ba0038d06b79c/regutil-app/src/test/reg.json#L3)):_

> ``` JSON
> {
> "name":"GoReg",
> "fullName":"A room registered by the GameOn registration tool.",
> ```

Longer room name

---

_[regutil-app/src/test/reg.json, line 4 [r2]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KM_XLRBKH-66-FTUlF6:-KM_XLRBKH-66-FTUlF7:-1090546007) ([raw file](https://github.com/gameontext/regutil/blob/3cfc5fca55ca958e106e7212a22ba0038d06b79c/regutil-app/src/test/reg.json#L4)):_

> ``` JSON
> "name":"GoReg",
> "fullName":"A room registered by the GameOn registration tool.",
> "description":"A not very interesting room which you can't connect to, but will show up in the list of sites if successfully registered.",
> ```

Boring default room description. Note the target IP: This room will not be reachable from the live site without updates.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1)_

**Comment by MarkNSweep** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[regutil-app/src/test/reg.json, line 4 [r2]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KM_XLRBKH-66-FTUlF6:-KM_fuzTLd6dGZIbej3K:-2067159592) ([raw file](https://github.com/gameontext/regutil/blob/3cfc5fca55ca958e106e7212a22ba0038d06b79c/regutil-app/src/test/reg.json#L4)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



> Boring default room description. Note the target IP: This room will not be reachable from the live site without updates.
> </details>
> This is not supposed to be anything more than a simple test case i.e. you currently use to verify the add, update and delete works. It's not intended to be used long term. You need to put something in the target IP that will be invalid in some form or another.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1)_

**Comment by MarkNSweep** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[regutil-app/src/test/reg.json, line 4 [r2]](https://reviewable.io:443/reviews/gameontext/regutil/1#-KM_XLRBKH-66-FTUlF6:-KM_gjoQTy3x6SdsmiMc:-1758048629) ([raw file](https://github.com/gameontext/regutil/blob/3cfc5fca55ca958e106e7212a22ba0038d06b79c/regutil-app/src/test/reg.json#L4)):_
<details><summary>

<i>Previously, MarkNSweep (Adam Pilkington) wrote…</i></summary>



> This is not supposed to be anything more than a simple test case i.e. you currently use to verify the add, update and delete works. It's not intended to be used long term. You need to put something in the target IP that will be invalid in some form or another.
> </details>
> Ignore my last comment, I get what you mean now.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1)_

**Comment by ebullient** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/regutil/1#-:-KMdtazLxpL_pSjF_zF1:1417088721)_

**Pull request merged**
